[bootstrap.directories."/etc/systemd/system/systemd-binfmt.service.d"]
owner = "root"
group = "root"
mode = "0755"

[bootstrap.files."/etc/systemd/system/systemd-binfmt.service.d/override.conf"]
source = "system/wsl/systemd-binfmt.override.conf"
owner = "root"
group = "root"
mode = "0644"

[env]
WORKSTATION_WSL = "1"
